### ISSUE TITLE
Grade/rank showing 'None'

### ISSUE THREAD

**Issue by Purloins** [beer-psi/chuni-penguin#30]
Whenever I do a best30/recents/etc. command, everything works except the grade.
It will show 'None' instead of 'SSS, SS', etc.

![image](https://github.com/beerpiss/chuninewbot/assets/63997255/d048cce5-7760-4508-bb17-1cd5dddbdca4)

**Comment by beer-psi** [comment]
Fixed by https://github.com/beerpiss/chuninewbot/commit/2c28408815a470c41c40976a683956d32d4cede7

Previously, if you were hosting your own instance and didn't fill in the rank icons, all ranks would be None.
