### ISSUE TITLE
Token issues

### ISSUE THREAD

**Issue by IanChen4516** [beer-psi/chuni-penguin#31]
I pasted my token in the chunirec_token line but it keeps saying that there is missing key
i even tried https://api.chunirec.net/2.0/music/showall.json?token={token}&region=jp2 and it works, 
don't know if its a bug or my problem
![image](https://github.com/beerpiss/chuninewbot/assets/93422643/446a0b28-bc8a-4cb9-b6b1-963ed1943f44)

**Comment by beer-psi** [comment]
How did you put the token? It should be like this in `bot.ini`:
```ini
[credentials]
# Used for retrieving data from https://db.chunỉrec.net
# Get one from https://developer.chunirec.net/
chunirec_token = abcdefghijklmnopqrs
```

The token shouldn't have any quotes.

You can also use the [hosted instance](https://discord.com/oauth2/authorize?client_id=1091948342101155950&scope=bot+applications.commands&permissions=274877983744) of the bot instead, apologies for not mentioning it before.

**Comment by IanChen4516** [comment]
i putted the token just as you said but it didn't work ,
![pic](https://github.com/beerpiss/chuninewbot/assets/93422643/38032961-2475-47f9-b6a2-f7fc26ea58ff)
also thanks for the discord bot

**Comment by beer-psi** [comment]
> i putted the token just as you said but it didn't work , ![pic](https://private-user-images.githubusercontent.com/93422643/313480330-38032961-2475-47f9-b6a2-f7fc26ea58ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDM0NjQsIm5iZiI6MTcxMDcwMzE2NCwicGF0aCI6Ii85MzQyMjY0My8zMTM0ODAzMzAtMzgwMzI5NjEtMjQ3NS00N2Y5LWI2YTItZjdmYzI2ZWE1OGZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE5MTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhMzNmM2FlNjlkYThkODljZTdkNWRlNzQyMjU2YjY0YTFmODAyODYzNTk0Mjg2YTUzNGYwNmZjYTFkMTYyOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8fX2FroTxKoN698uJs_zqakkPkdNR086hoEu75pdsKE) also thanks for the discord bot

You forgot to uncomment the configuration. Remove the `#` at the start of the `chunirec_token` line.

**Comment by IanChen4516** [comment]
Oh mybad

beerpsi ***@***.***> 於 2024年3月18日 週一 上午3:20 寫道：
