### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'chuninet'

### ISSUE THREAD

**Issue by Purloins** [beer-psi/chuni-penguin#32]
File "/home/container/.local/lib/python3.12/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/cogs/chunithm/records.py", line 48, in recent
    ctxmgr = self.utils.chuninet(ctx if user is None else user.id)
             ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'chuninet'

**Comment by beer-psi** [comment]
This should only happen if the utilities cog failed to load. Can you send me the bot logs (`chuninewbot.log`)?

**Comment by Purloins** [comment]
[chuninewbot.log](https://github.com/beerpiss/chuninewbot/files/14658936/chuninewbot.log)

**Comment by beer-psi** [comment]
> [chuninewbot.log](https://github.com/beerpiss/chuninewbot/files/14658936/chuninewbot.log)

You haven't migrated the database to the latest version. Run `alembic upgrade head` in the bot's virtual environment.
